window.$ = window.jQuery = require('jquery/dist/jquery')
window.M = require('materialize-css/dist/js/materialize')
window.hljs = require('highlight.js')
window.moment = require('moment/moment')
window.ProgressBar = require('progressbar.js/dist/progressbar')
require('./script')