require('./bootstrap')
require('materialize-css/dist/js/materialize')
window.moment = require('moment/moment')
window.ProgressBar = require('progressbar.js/dist/progressbar')
window.hljs = require('highlight.js')